-- Schema Room&Relax (Italiano)
create table if not exists camere (
  id bigint generated by default as identity primary key,
  nome text not null,
  descrizione text,
  prezzo numeric(10,2) not null,
  immagine text,
  disponibile boolean default true
);

create table if not exists prenotazioni (
  id bigint generated by default as identity primary key,
  camera_id bigint references camere(id) on delete cascade,
  nome text not null,
  cognome text not null,
  telefono text,
  email text not null,
  data_inizio date not null,
  data_fine date not null,
  data_prenotazione timestamp default now()
);

create table if not exists closures (
  id bigint generated by default as identity primary key,
  camera_id bigint references camere(id) on delete cascade,
  start_date date not null,
  end_date date not null,
  note text
);

create table if not exists admin_settings (
  id bigint generated by default as identity primary key,
  password text not null
);

insert into admin_settings (id, password) values (1, 'admin') on conflict (id) do nothing;

-- Seed camere
insert into camere (nome, descrizione, prezzo, immagine, disponibile) values
('Camera Sole', 'Doppia con vista e balcone', 80.00, 'https://picsum.photos/seed/sole/800/600', true),
('Camera Mare', 'Matrimoniale vicino al mare', 75.00, 'https://picsum.photos/seed/mare/800/600', true),
('Camera Relax', 'Camera con bagno privato', 85.00, 'https://picsum.photos/seed/relax/800/600', true),
('Camera Luna', 'Singola accogliente', 60.00, 'https://picsum.photos/seed/luna/800/600', true)
on conflict do nothing;
